### PR TITLE
Add `flatc` for Linux x64

### PR DESCRIPTION
**Pull request by TheDevMinerTV**
## Description

This binary is statically linked and stripped :)

## QA

- Run this binary on Linux and check if it runs

### CODE REVIEW

**Comment by TheButlah** [comment]
Providing flatc was just for people super unfamilar with flatbuffers and not comfortable with cmake. I would expect linux users to be perfectly comfortable with cmake and able to build themselves

**Comment by Eirenliel** [comment]
Ideally we shouldn't provide binaries but clear instructions for platforms on how to set stuff up.

**Comment by loucass003** [comment]
Problem is that rn the lastest build for flatc is not working with our project. We have to grab a build from one of their lastest artifacts that is not a release.

**Comment by TheDevMinerTV** [comment]
> Ideally we shouldn't provide binaries but clear instructions for platforms on how to set stuff up.

I sure as hell ain't gonna be the one teaching people on windows how to compile stuff. LOL

**Comment by Louka3000** [comment]
> > Ideally we shouldn't provide binaries but clear instructions for platforms on how to set stuff up.
> 
> I sure as hell ain't gonna be the one teaching people on windows how to compile stuff. LOL Linux on the other hand: sure, that's pretty easy

It’s fine I’ll ask Thebutlah  or Futura :p

**Review by TheButlah — CHANGES_REQUESTED** [review]
I think we should close this, and instead improve the "how to build with cmake" documentation. LMK if you agree, @TheDevMinerTV

**Comment by TheDevMinerTV** [comment]
We should reinvestigate this, especially with @TheButlah using an outdated / non-matching version of `flatc`.

**Comment by TheButlah** [comment]
Nope, and the flatc I used was on mac. We don't need to bundle these things.

**Comment by loucass003** [comment]
we did it for windows .... i dont get why we should not do it for the rest .... 
Nothing prevents anybody to use the version on their computer anyway. We would just recomend to use the one with the repo to make sur the version is the same

**Comment by TheDevMinerTV** [comment]
> Nope, and the flatc I used was on mac.

Does that matter? Compile `flatc` and include it here as well.

**Comment by TheButlah** [comment]
Will close soon unless there is further discussion necessary

**Pull request closed without merging**
