### PR TITLE
Add hands to steamvr trackers

### PR DESCRIPTION
**Pull request by Louka3000**

### CODE REVIEW

**Comment by TheButlah** [comment]
Something is weird about this PR: there was only a tiny change in the schema but tons of the code was regenerated.
@Louka3000 are you sure you're using the version of flatc in the readme, and are you sure you committed all of the schema files?

**Comment by Louka3000** [comment]
Last PR (for legtweaks) didn't generate the files. You merged that PR :nya_a:

**Comment by TheButlah** [comment]
https://media.tenor.com/MYZgsN2TDJAAAAAC/this-is.gif

**Review by TheButlah — APPROVED** [review]

**Pull request merged**
