### PR TITLE
Nixify solarxr

### PR DESCRIPTION
**Pull request by ImUrX**
Added ``nix`` scripts that will auto-fetch needed build tools for SolarXR :P

### CODE REVIEW

**Comment by TheButlah** [comment]
I need more of an explanation

**Comment by ImUrX** [comment]
If you have the nix package manager, you can do ``nix develop`` and you will have flatbuffers in your path with the correct version needed.
If you also have ``direnv`` it will automatically do ``nix develop`` when you enter the project (you need to trust it in direnv with ``direnv allow`` tho)

**Comment by loucass003** [comment]
there is not that many people on nixos. on the other hand it is not changing anything for the people that does not use it. if it helps even 1 person here I would say it is a good thing to have it

**Comment by ImUrX** [comment]
btw, i honestly dont want to solve this. But I can't even run flatc downloaded from github releases (both of them)

**Review by loucass003 — APPROVED** [review]

**Comment by TheButlah** [comment]
Sounds good to me. As long as @ImUrX will maintain it

**Pull request merged**
