### PR TITLE
Change OSC address field to string

### PR DESCRIPTION
**Pull request by loucass003**
Change address field to string for simpler usage and allowing using local hostnames

### CODE REVIEW

**Comment by TheButlah** [comment]
I need to look into OSC first before approving, I'm not sure I agree with the rationale but I'll check

**Comment by loucass003** [comment]
> I need to look into OSC first before approving, I'm not sure I agree with the rationale but I'll check

Most of the problem is that decoding and encoding that ip address from a string is a PAIN especially from javascript
In the datafeed it makes sense to save bandwidth and the only thing we do is reading the value but with osc we have to parse the ip then encoding the ip to then decoding it anyway on the server back to a string

**Comment by TheButlah** [comment]
Here are my concerns basically:
1. if its a string, its not necessarily 127.0.0.1, it can be localhost, it can be www.domain.com, it can be tcp://192.168.1.1. I don't want to risk applications having non-standard ways of specifying it - this should only be the ip and not the scheme, fragment, port, DNS domain, or other things people might shove in that string.
2. Its not true that its unbearably difficult to parse this in javascript. Just write a function XD
3. I don't like stringly typed apis

Also I need to look into how we specify an osc endpoint. I am not sure how to do that yet, haven't looked. Will look this weekend.

**Comment by Eirenliel** [comment]
.local domains exist and are very useful, an ability to run OSC to remote client can aslo be useful. parsing URL in Java is trivial, we can easily find if it's full schema, ip or domain, as well as do DNS lookup. it should also be trivial in JS, i'm sure if it's needed, but i don't see the reason not to send a string and handle it on the side of the server...

**Comment by TheButlah** [comment]
Well the server already was released with this in the submodule.

I *really* don't want to make that a habit. I know it was an accident and that we were scrambling today to get a v0.4.0, but in the general case, obviously we should avoid cutting releases to protocols that don't exist on `main`

Going to approve on that basis alone but if it happens again I'll travel back to france and poop on @loucass003's bed

**Review by TheButlah — APPROVED** [review]

**Comment by Eirenliel** [comment]
I will keep insisting it's correct anyway.

**Pull request merged**
